import { createApp } from "vue";
import router from "./router/router";
import vuetify from "./plugins/vuetify";
import { createPinia } from "pinia";
import Vue3Transitions from "vue3-transitions";
import "./style.css";
const pinia = createPinia();
import App from "./App.vue";
import { loadFonts } from "./plugins/fontLoader";
const app = createApp(App);
app.use(Vue3Transitions);
app.use(pinia);
app.use(router);
app.use(vuetify);
app.mount("#app");
